//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aitisis
    {
        public int AitisisID { get; set; }
        public Nullable<System.DateTime> AitisisDate { get; set; }
        public string AitisisProtocol { get; set; }
        public Nullable<int> ProkirixisID { get; set; }
        public string TeacherAFM { get; set; }
        public Nullable<int> Klados { get; set; }
        public Nullable<int> Eidikotita { get; set; }
        public Nullable<int> BasicEducation { get; set; }
        public Nullable<int> PtyxioType { get; set; }
        public string PtyxioTitlos { get; set; }
        public Nullable<int> PtyxioYear { get; set; }
        public Nullable<decimal> PtyxioGrade { get; set; }
        public string PtyxioInstitution { get; set; }
        public string PtyxioSchool { get; set; }
        public string PtyxioTmima { get; set; }
        public Nullable<bool> PtyxioForeign { get; set; }
        public Nullable<bool> PtyxioAnagnorisi { get; set; }
        public string PtyxioFilename { get; set; }
        public string PtyxioAnagnorisiFilename { get; set; }
        public string MscTitlos { get; set; }
        public Nullable<int> MscYear { get; set; }
        public string MscInstitution { get; set; }
        public Nullable<int> MscSynafeia { get; set; }
        public Nullable<bool> MscForeign { get; set; }
        public Nullable<bool> MscAnagnorisi { get; set; }
        public string MscFilename { get; set; }
        public string MscAnagnorisiFilename { get; set; }
        public string PhdTitlos { get; set; }
        public Nullable<int> PhdYear { get; set; }
        public string PhdInstitution { get; set; }
        public Nullable<int> PhdSynafeia { get; set; }
        public Nullable<bool> PhdForeign { get; set; }
        public Nullable<bool> PhdAnagnorisi { get; set; }
        public string PhdFilename { get; set; }
        public string PhdAnagnorisiFilename { get; set; }
        public Nullable<int> EpagelmaCategory { get; set; }
        public Nullable<int> Periferia { get; set; }
        public Nullable<int> School { get; set; }
        public Nullable<decimal> MoriaPtyxio { get; set; }
        public Nullable<decimal> MoriaMsc { get; set; }
        public Nullable<decimal> MoriaPhd { get; set; }
        public Nullable<decimal> MoriaLanguage { get; set; }
        public Nullable<decimal> MoriaComputer { get; set; }
        public Nullable<decimal> MoriaEpimorfosi { get; set; }
        public Nullable<decimal> MoriaCertified { get; set; }
        public Nullable<decimal> MoriaTeach { get; set; }
        public Nullable<decimal> MoriaWork { get; set; }
        public Nullable<decimal> MoriaAnergia { get; set; }
        public Nullable<decimal> MoriaSocial { get; set; }
        public Nullable<decimal> MoriaTotal { get; set; }
        public Nullable<bool> OaedPtyxioConfirm { get; set; }
        public Nullable<bool> OaedMscConfirm { get; set; }
        public Nullable<bool> OaedPhdConfirm { get; set; }
        public Nullable<System.DateTime> OaedMoriodotisiDate { get; set; }
        public Nullable<bool> OaedApoklismos { get; set; }
        public Nullable<int> OaedApoklismosAitia { get; set; }
        public string OaedEpitropi1Text { get; set; }
        public string OaedEpitropi2Text { get; set; }
        public Nullable<bool> OaedCheckStatus { get; set; }
        public Nullable<bool> OaedEnstasi { get; set; }
        public Nullable<int> EidikotitaGroup { get; set; }
    
        public virtual Teachers Teachers { get; set; }
    }
}
