//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AitisiSchools
    {
        public int RowID { get; set; }
        public int AitisiID { get; set; }
        public int SchoolID { get; set; }
        public int PeriferiaID { get; set; }
    }
}
