//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Epimorfosis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Epimorfosis()
        {
            this.EpimorfosiFiles = new HashSet<EpimorfosiFiles>();
        }
    
        public int EpimorfosiID { get; set; }
        public string EpimorfosiTitlos { get; set; }
        public string EpimorfosiForeas { get; set; }
        public Nullable<int> EpimorfosiType { get; set; }
        public Nullable<int> EpimorfosiHours { get; set; }
        public Nullable<System.DateTime> EpimorfosiDateStart { get; set; }
        public Nullable<System.DateTime> EpimorfosiDateFinal { get; set; }
        public string TeacherAfm { get; set; }
        public Nullable<int> ProkirixiID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EpimorfosiFiles> EpimorfosiFiles { get; set; }
    }
}
