//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpimorfosiFiles
    {
        public int UploadFileID { get; set; }
        public string Filename { get; set; }
        public string Description { get; set; }
        public string Filepath { get; set; }
        public Nullable<int> EpimorfosiID { get; set; }
    
        public virtual Epimorfosis Epimorfosis { get; set; }
    }
}
