//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryFinalWork
    {
        public long RowID { get; set; }
        public Nullable<int> AitisiID { get; set; }
        public Nullable<int> ProkirixiID { get; set; }
        public Nullable<decimal> MoriaTotal { get; set; }
    }
}
