//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlAitisiData
    {
        public int AitisisID { get; set; }
        public string AitisisProtocol { get; set; }
        public string PeriferiaName { get; set; }
        public string SchoolName { get; set; }
        public string TeacherAFM { get; set; }
        public string FullName { get; set; }
        public string KladosEidikotita { get; set; }
        public string PtyxioTypeText { get; set; }
        public string PtyxioTitlos { get; set; }
        public string MscTitlos { get; set; }
        public string PhdTitlos { get; set; }
        public string Ptyxio2Titlos { get; set; }
        public string Language1Epipedo { get; set; }
        public string Language2Epipedo { get; set; }
        public string ComputerTitle { get; set; }
        public int EpimorfosiHours { get; set; }
        public string CertifiedTrainerAM { get; set; }
        public string SocialTriteknosText { get; set; }
        public string SocialPolyteknosText { get; set; }
        public string SocialSingleParentText { get; set; }
        public string SocialAmeaText { get; set; }
        public string AnergiaDiarkeiaText { get; set; }
        public decimal MoriaPtyxio { get; set; }
        public decimal MoriaMsc { get; set; }
        public decimal MoriaPhd { get; set; }
        public decimal MoriaLanguages { get; set; }
        public decimal MoriaComputer { get; set; }
        public decimal MoriaEpimorfosi { get; set; }
        public decimal MoriaCertified { get; set; }
        public decimal MoriaTeach { get; set; }
        public decimal MoriaWork { get; set; }
        public decimal MoriaAnergia { get; set; }
        public decimal MoriaSocial { get; set; }
        public decimal MoriaTotal { get; set; }
        public string EpagelmaText { get; set; }
        public Nullable<int> ProkirixisID { get; set; }
    }
}
