//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlAitisiProsonta
    {
        public int AitisisID { get; set; }
        public string TeacherAFM { get; set; }
        public Nullable<int> PtyxioType { get; set; }
        public Nullable<int> Ptyxio2Type { get; set; }
        public Nullable<int> MscSynafeia { get; set; }
        public Nullable<int> PhdSynafeia { get; set; }
        public Nullable<int> Language1 { get; set; }
        public Nullable<int> Language1Level { get; set; }
        public Nullable<int> Language2 { get; set; }
        public Nullable<int> Language2Level { get; set; }
        public Nullable<int> ComputerCertificate { get; set; }
        public Nullable<int> EpimorfosiTotalHours { get; set; }
        public Nullable<bool> CertifiedTrainer { get; set; }
        public Nullable<bool> SocialTriteknos { get; set; }
        public Nullable<bool> SocialPolyteknos { get; set; }
        public Nullable<bool> SocialSingleParent { get; set; }
        public Nullable<bool> SocialAmea { get; set; }
        public Nullable<int> SocialAnergos { get; set; }
        public Nullable<bool> OaedPtyxioConfirm { get; set; }
        public Nullable<bool> OaedPtyxio2Confirm { get; set; }
        public Nullable<bool> OaedMscConfirm { get; set; }
        public Nullable<bool> OaedPhdConfirm { get; set; }
        public Nullable<bool> OaedLanguage1Confirm { get; set; }
        public Nullable<bool> OaedLanguage2Confirm { get; set; }
        public Nullable<bool> OaedComputerConfirm { get; set; }
        public Nullable<bool> OaedEpimorfosiConfirm { get; set; }
        public Nullable<bool> OaedCertifiedConfirm { get; set; }
    }
}
