//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlAitisiSelector
    {
        public int AitisisID { get; set; }
        public Nullable<int> ProkirixisID { get; set; }
        public string TeacherAFM { get; set; }
        public string AitisisInfo { get; set; }
    }
}
