//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlEidikotitesSelector
    {
        public int EidikotitaID { get; set; }
        public string EidikotitaDesc { get; set; }
        public Nullable<int> EidikotitaKladosID { get; set; }
        public Nullable<int> EidikotitaGroupID { get; set; }
    }
}
