//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlPeriferiesSchools
    {
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public Nullable<int> SchoolPeriferiaID { get; set; }
        public string PeriferiaName { get; set; }
    }
}
