//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlTeacherAitiseis
    {
        public int AitisisID { get; set; }
        public string AitisisProtocol { get; set; }
        public Nullable<int> ProkirixisID { get; set; }
        public string Protocol { get; set; }
        public string TeacherAFM { get; set; }
        public string FullName { get; set; }
        public string EidikotitaText { get; set; }
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public int PeriferiaID { get; set; }
        public string PeriferiaName { get; set; }
        public int PeriferiakiID { get; set; }
        public string PeriferiakiName { get; set; }
        public Nullable<bool> OaedCheckStatus { get; set; }
        public Nullable<bool> OaedEnstasi { get; set; }
    }
}
