//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlTeachersRegistry
    {
        public string AFM { get; set; }
        public string FullName { get; set; }
        public string Telephone { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string FullAddress { get; set; }
        public Nullable<int> Idiotita { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
