//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlUserTeacherSelect
    {
        public int UserID { get; set; }
        public string UserAfm { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string FullName { get; set; }
    }
}
