//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysAnergia
    {
        public int AnergiaID { get; set; }
        public string AnergiaText { get; set; }
        public Nullable<decimal> AnergiaMoria { get; set; }
    }
}
