//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysLanguageLevel
    {
        public int LevelID { get; set; }
        public string LevelText { get; set; }
        public Nullable<decimal> MoriaFirst { get; set; }
        public Nullable<decimal> MoriaSecond { get; set; }
    }
}
