//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysSchools
    {
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public string SchoolEmail { get; set; }
        public Nullable<int> SchoolTypeID { get; set; }
        public Nullable<int> SchoolPeriferiaID { get; set; }
        public Nullable<int> SchoolPeriferiakiID { get; set; }
    
        public virtual SysPeriferiakes SysPeriferiakes { get; set; }
        public virtual SysPeriferies SysPeriferies { get; set; }
    }
}
