//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysTaxFree
    {
        public int YearID { get; set; }
        public string YearText { get; set; }
        public Nullable<float> TaxFree { get; set; }
        public string Nomisma { get; set; }
    }
}
