//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherSkills
    {
        public int SkillsID { get; set; }
        public string TeacherAFM { get; set; }
        public Nullable<int> Ptyxio2Type { get; set; }
        public string Ptyxio2Titlos { get; set; }
        public Nullable<int> Ptyxio2Year { get; set; }
        public string Ptyxio2Institution { get; set; }
        public Nullable<bool> Ptyxio2Foreign { get; set; }
        public Nullable<bool> Ptyxio2Anagnorisi { get; set; }
        public string Ptyxio2Filename { get; set; }
        public string Ptyxio2AnagnorisiFilename { get; set; }
        public Nullable<int> Language1 { get; set; }
        public Nullable<int> Language1Level { get; set; }
        public string Language1Titlos { get; set; }
        public string Language1Filename { get; set; }
        public Nullable<int> Language2 { get; set; }
        public Nullable<int> Language2Level { get; set; }
        public string Language2Titlos { get; set; }
        public string Language2Filename { get; set; }
        public Nullable<int> ComputerCertificate { get; set; }
        public string ComputerTitlos { get; set; }
        public Nullable<int> ComputerYear { get; set; }
        public string ComputerFilename { get; set; }
        public Nullable<bool> Epimorfosi { get; set; }
        public Nullable<int> EpimorfosiTotalHours { get; set; }
        public Nullable<bool> CertifiedTrainer { get; set; }
        public string CertifiedTrainerAM { get; set; }
        public string CertifiedTrainerFilename { get; set; }
        public Nullable<bool> N2190Protect { get; set; }
        public string N2190ProtectFilename { get; set; }
        public Nullable<bool> OaedPtyxio2Confirm { get; set; }
        public Nullable<bool> OaedLanguage1Confirm { get; set; }
        public Nullable<bool> OaedLanguage2Confirm { get; set; }
        public Nullable<bool> OaedComputerConfirm { get; set; }
        public Nullable<bool> OaedEpimorfosiConfirm { get; set; }
        public Nullable<bool> OaedCertifiedConfirm { get; set; }
        public Nullable<bool> OaedN2190Confirm { get; set; }
    
        public virtual Teachers Teachers { get; set; }
    }
}
