//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachersUploads
    {
        public int UploadFileID { get; set; }
        public string TeacherAFM { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public string Description { get; set; }
        public string SchoolYearText { get; set; }
    }
}
