//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PegasusPlus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTeaching
    {
        public int ExperienceID { get; set; }
        public Nullable<int> AitisiID { get; set; }
        public Nullable<int> ProkirixiID { get; set; }
        public Nullable<int> TeachType { get; set; }
        public Nullable<int> SchoolYear { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateFinal { get; set; }
        public Nullable<int> HoursWeek { get; set; }
        public Nullable<int> HoursTotal { get; set; }
        public Nullable<decimal> Moria { get; set; }
        public string DocumentProtocol { get; set; }
        public string DocumentForeas { get; set; }
        public Nullable<bool> Valid { get; set; }
    }
}
